### ISSUE TITLE
Manually index

### ISSUE THREAD

**Issue by telezoic** [DigitalNZ/supplejack_docker#6] opened 2016-11-02 18:19 UTC
Hi @hapiben, 

I have the stack running now and have created some parser scripts. Supplejack is a joy to use. Thanks for all your help with this. In the readme, you note that indexing (to the api?) could be done manually. Is this done at the console or is there a place in the manager interface for this? 

I have tried to schedule a harvest via the manager [staging schedule], without effect from what I can see - nothing in Solr or the API url. 

Do you have any suggestions to move me in the right direction? 

Thanks, 

D

**Comment by hapiben** [comment] 2016-11-02 22:20
Hi @telezoic,

It's great that it works!

Currently, scheduled harvesting is not yet configured. I will work on this tomorrow.

There's a small issue I found when running a normal harvest. The issue is that API cannot connect to Redis. Fixed on this [commit](https://github.com/DigitalNZ/supplejack_api_app/commit/3ac080cfe33cc5e033309127f914b11378911862). Just pull the latest changes recursively from `supplejack_docker` repo.

For the API indexing, you can do manual Solr indexing by following these steps.

- Make sure all containers are running
- Run `docker exec -it api /bin/bash` to get inside the API container
- Run `rails c` to get into API's rails console
- Verify the harvested records count by running `SupplejackApi::Record.count`
- Build Solr session by running `Sunspot.session = Sunspot::Rails.build_session`
- Index all records `SupplejackApi::Record.all.map(&:index)`
- Commit Solr index `Sunspot.commit`

You should be able to see the records in the API by accessing the API in the browser using the default API key. 

Two things I'll work on tomorrow is the Resque for API to allow automatic indexing and the scheduled harvesting.

If you got issues, please let me know.

**Comment by hapiben** [comment] 2016-11-06 22:14
Hi @telezoic,

I'm still working on the scheduled harvest. Did you managed to index your records manually?

Ben

**Comment by telezoic** [comment] 2016-11-07 05:56
Hi @hapiben,

Thanks for asking, I pulled the changes, but I have yet to try it.
I’m at a conference this week in Milwaukee, so I hope to get a chance in the next few days. I’ll let you know how it goes.


D.



On Nov 6, 2016, at 2:14 PM, Ben <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi @telezoic<https://github.com/telezoic>,

I'm still working on the scheduled harvest. Did you managed to index your records manually?

Ben

**Comment by telezoic** [comment] 2016-11-07 19:47
Hi @hapiben,

I can preview items without trouble, but if the scheduler for the harvest isn’t working, can you tell me how I execute the harvest? Setting the schedule to “Now” doesn’t seem to do anything.

Running SupplejackApi::Record.count at the console gives me =>0 which makes me think I’m missing something.

In the screencast, there’s a harvest button. I don’t have that in my manager interface.

Sorry to keep hammering you with new questions all the time. :)


Thanks,


D





On Nov 6, 2016, at 11:56 PM, Daniel Sifton <Daniel.Sifton@viu.ca<mailto:Daniel.Sifton@viu.ca>> wrote:

Hi @hapiben,

Thanks for asking, I pulled the changes, but I have yet to try it.
I’m at a conference this week in Milwaukee, so I hope to get a chance in the next few days. I’ll let you know how it goes.


D.



On Nov 6, 2016, at 2:14 PM, Ben <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi @telezoic<https://github.com/telezoic>,

I'm still working on the scheduled harvest. Did you managed to index your records manually?

Ben

**Comment by hapiben** [comment] 2016-11-07 23:23
Hi @telezoic,

You can run a run a harvest by following these step:

- On the sidebar, you'll see the history of changes of the parser.
- Click the latest one and tag it as staging.
- You'll then have the option from `Run Harvest` dropdown to do staging harvest.

Check out this [recording](http://recordit.co/x4EkY8jhy9).

**Note**: SJ Manager doesn't have development harvest. When you're in development or staging environment, the harvest environment to use is staging.

**Comment by telezoic** [comment] 2016-11-08 04:40
Brilliant!

Thank you. I’ve got it now.

Next,I think I will try and increase the complexity of the parser scripts I’ve created, and work on the schema.


D.



On Nov 7, 2016, at 5:23 PM, Ben <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi @telezoic<https://github.com/telezoic>,

You can run a run a harvest by following these step:

  *   On the sidebar, you'll see the history of changes of the parser.
  *   Click the latest one and tag it as staging.
  *   You'll then have the option from Run Harvest dropdown to do staging harvest.

Check out this recording<http://recordit.co/x4EkY8jhy9>.

Note: SJ Manager doesn't have development harvest. When you're in development or staging environment, the harvest environment to use is staging.

**Comment by hapiben** [comment] 2016-11-08 05:56
@telezoic Great! Just let me know if you have issues and I'll try my best. 👍

**Closed by hapiben** 2016-11-08 05:56 UTC
Labels: enhancement, question

**Comment by jamesarobertson** [comment] 2016-11-09 23:09
Thanks again @hapiben :-)

**Comment by hapiben** [comment] 2016-12-01 21:10
Hi @telezoic,

Just to give you an update, I've added Resque and Resque Scheduler containers as part of this repo. This means that you don't need to do a manual indexing after you do a harvest. Resque Scheduler runs the indexing every five minutes (configurable).

Checkout this [commit](https://github.com/DigitalNZ/supplejack_docker/commit/752a4e5c6e40a7ce38ed94650d3977d0d88ae354#diff-4e5e90c6228fd48698d074241c2ba760) for more details.

Ben

**Comment by telezoic** [comment] 2016-12-01 23:05
This is great Ben. Thanks! I'm at a conference demoing Supplejack for folks here in BC. I will share this with interested folks here (there are many)  and try it out next week.

D.

On Dec 1, 2016, at 13:10, Ben <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi @telezoic<https://github.com/telezoic>,

Just to give you an update, I've added Resque and Resque Scheduler containers as part of this repo. This means that you don't need to do a manual indexing after you do a harvest. Resque Scheduler runs the indexing every five minutes (configurable).

Checkout this commit<https://github.com/DigitalNZ/supplejack_docker/commit/752a4e5c6e40a7ce38ed94650d3977d0d88ae354#diff-4e5e90c6228fd48698d074241c2ba760> for more details.

Ben

�
